[Unit]
Requires=onekvm-machine-nanokvm-detect.service
Wants=onekvm-video-soph-mmf-modules.service onekvm-device-gpio-atx.service
After=onekvm-machine-nanokvm-detect.service onekvm-video-soph-mmf-modules.service
