[Unit]
Requires=onekvm-machine-nanokvm-detect.service
Wants=onekvm-device-nanokvm-mmf-modules.service onekvm-device-gpio-atx.service
After=onekvm-machine-nanokvm-detect.service onekvm-device-nanokvm-mmf-modules.service
